basePath: /
definitions:
  model.Car:
    properties:
      car_rfid_id:
        type: integer
      color:
        type: string
      flag:
        type: string
      id:
        type: integer
      master_id:
        type: integer
      plate_number:
        type: string
      start_time:
        type: string
      type:
        type: string
    type: object
  model.Master:
    properties:
      id:
        type: integer
      id_number:
        type: string
      mobile_number:
        type: string
      name:
        type: string
      nickname:
        type: string
      open_id:
        type: string
      register_time:
        type: string
    type: object
  model.Position:
    properties:
      id:
        type: integer
      position:
        type: string
      rfid_id:
        type: integer
    type: object
  model.RFID:
    properties:
      car_rfid_id:
        type: integer
      id:
        type: integer
      rfid_id:
        type: integer
      time:
        type: string
    type: object
  request.ChangePasswd:
    properties:
      id:
        type: integer
      newPasswd:
        type: string
      password:
        type: string
    type: object
  request.Login:
    properties:
      nickname:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  description: Auto-Manager 的接口设置完全遵循Restful原则，具体参考API文档
  title: Auto-Manager Dev API
  version: 0.0.1
paths:
  /v1/base/token:
    post:
      parameters:
      - description: nickname, password
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "201":
          description: '{"success":true, "data":{}, "msg":"登录成功"}'
          schema:
            type: string
      summary: 管理员登录
      tags:
      - base
  /v1/car:
    get:
      produces:
      - application/json
      responses:
        "201":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 新增记录
      tags:
      - 待完成
    post:
      parameters:
      - description: rfid与车辆id的映射
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.RFID'
      produces:
      - application/json
      responses:
        "201":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 新增记录
      tags:
      - 待完成
  /v1/car/:id:
    delete:
      parameters:
      - description: id
        in: body
        name: data
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "201":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 新增记录
      tags:
      - 待完成
    put:
      parameters:
      - description: 完整Car信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Car'
      produces:
      - application/json
      responses:
        "201":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 修改车辆信息
      tags:
      - 待完成
  /v1/manager:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true, "data":{}, "msg":""}'
          schema:
            type: string
      summary: 获取管理员列表
      tags:
      - manager
  /v1/manager/:id/passwd:
    put:
      parameters:
      - description: id, passwd, passwdNew
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ChangePasswd'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true, "data":{}, "msg":"修改成功"}'
          schema:
            type: string
      summary: 管理员密码修改
      tags:
      - manager
  /v1/master:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 待完成
  /v1/master/:id:
    delete:
      parameters:
      - description: id
        in: body
        name: data
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 注销账户
      tags:
      - 待完成
    put:
      parameters:
      - description: 完整的用户信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Master'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 用户信息修改
      tags:
      - 待完成
  /v1/master/token:
    post:
      parameters:
      - description: 暂定OpenID
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true, "data":{}, "msg":"登录成功"}'
          schema:
            type: string
      summary: 微信小程序认证
      tags:
      - 待完成
  /v1/position:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 获取RFID与地址对应表
      tags:
      - position
    post:
      parameters:
      - description: -, rfid_id, position
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Position'
      produces:
      - application/json
      responses:
        "201":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 新增RFID与地址关系
      tags:
      - position
  /v1/position/:id:
    delete:
      produces:
      - application/json
      responses:
        "204":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 删除RFID与地址关系
      tags:
      - position
    put:
      parameters:
      - description: -, rfid_id, position
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Position'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true, "data":{}, "msg":"成功"}'
          schema:
            type: string
      summary: 修改RFID与地址关系
      tags:
      - position
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
